### ISSUE TITLE
Bugged accessories when combining

### ISSUE THREAD

**Issue by RECCASTWIN** [Majrusz/MajruszsAccessories#22] opened 2023-10-17 19:16 UTC
it's basically the same as R3TR0xSN1P3R's issue where combining things breaks aforementioned things
![image](https://github.com/Majrusz/MajruszsAccessories/assets/91829887/bac6d764-cb0a-4937-8a39-0f3756d6537a)

**Comment by RECCASTWIN** [comment] 2023-10-18 15:57
The combining works, but it breaks because of Crafting Tweaks by BlayTheNinth
![image](https://github.com/Majrusz/MajruszsAccessories/assets/91829887/fd3051b8-eaf0-4918-b560-d7e7c6ab531c)

**Comment by Majrusz** [comment] 2023-10-30 19:25
Hello, thanks for the report, as it is a duplicate of this https://github.com/Majrusz/MajruszsAccessories/issues/21 I will close this one

**Closed as completed by Majrusz** 2023-10-30 19:25 UTC
Labels: bug, duplicate, 1.20.X
